#!/bin/bash
#
# accept eula if set
#
# (c) 2016 nimmis <kjell.havneskold@gmail.com>
# (c) 2017 OwnageTechGeek <talentcmc@gmx.com>

# I don't really want to have to agree to the damn EULA every single time.  I agree.
  
  echo "eula=$EULA" > $SPIGOT_HOME/eula.txt
  chown minecraft $SPIGOT_HOME/eula.txt 

fi 
